language: r
sudo: required
dist: trusty

cache: packages

r_packages:
  - wrswoR
  - ipfp
  - covr

notifications:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr); codecov()'
